server:
  port: 9001
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: 391f529f-181f-4c58-9b05-1ef36a0af9c3
    gateway:
      routes:
        - id: ware-service-route # 路由的唯一id
          uri: lb://ware-service  # 转发到指定服务，默认lb是轮询
          # 谓词配置
          predicates:
            - Path=/ware-service/** # 代表用户端URI如果以/ware-service开头便会转发到service-a实例
            - After=2024-02-09T00:00:00.000+08:00[Asia/Shanghai] # #After生效时间谓词，2024年2月9日后该路由才能在网关对外暴露
          filters:
            # 例如请求：http://localhost:9001/ware-service/ware/get/10001，转发过去的请求会是/ware-service/ware/get/10001，
            # 而实际路径是/ware/get/{id}，此时可以选择忽略第一层路径
            - StripPrefix=1 # 请求转发时忽略掉第一层路径
            # x`x`涉及过滤器参数时，采用name-args的完整写法
            - name: Retry #name是内置的过滤器名
              args: #参数部分使用args说明
                retries: 3
                status: 503
#      discovery:
#        locator:
#          enabled: true # 自动根据URL规则实现路由转发, 一般不用
management:
  endpoints:
    web:
      exposure:
        include: '*' # 对外暴露actuator所有监控指标，便于监控系统收集跟踪，酌情考虑，防止暴露接口
debug: true