server:
  port: 8201
spring:
  application:
    name: consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.1:8848
        username: nacos
        password: nacos
        namespace: 391f529f-181f-4c58-9b05-1ef36a0af9c3
# ribbon得默认负载均衡是轮询，可以通过下面这种方式选择负载均衡策略
provider-service: # 服务名
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 策略类