server:
  port: 8101
spring:
  application:
    name: provider-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.1:8848
        username: nacos
        password: nacos
        namespace: 391f529f-181f-4c58-9b05-1ef36a0af9c3