apollo:
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application.properties
  cache-dir: classpath:/apolloCache
  meta: http://192.168.5.1:8080
app:
  id: apollo-config
