#server:
#  port: 8001
#spring:
#  application:
#    name: nacos-sample-server
#  cloud:
#    nacos:
#      discovery:
##        server-addr: 192.168.194.162:8848
#        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos